api/v1/work_order/urls.py
from django.urls import path, re_path
from . import views

app_name = 'api_v1_work_order'

urlpatterns = [
    re_path(r'model-no-based-products/(?P<model_no>.*)/$',views.model_number_based_products),
    re_path(r'order-model-numbers/$',views.order_model_numbers),
    
    re_path(r'workorder-details', views.work_order),
    re_path(r'create-work-orders', views.work_order_create),
    # re_path(r'workorder-details/(?P<pk>.*)/$',views.work_order),
    re_path(r'workorder-details/(?P<id>\d+)/$', views.work_order),
    
    re_path(r'work-assign-status',views.work_assign_status),
    re_path(r'work-order-assign/(?P<pk>.*)/$',views.work_order_assign),
    
    re_path(r'work_order_staff_assign/(?P<pk>.*)/$',views.work_order_staff_assign),
    
    re_path(r'add_accessory_to_work_order/(?P<pk>.*)/$',views.add_accessory_to_work_order),
    
    re_path(r'^dispatch/$', views.dispatch_details),
    re_path(r'^dispatch_details/(?P<pk>.*)/$', views.dispatch_details),
    # re_path(r'carpentary-assign/(?P<pk>.*)/$',views.assign_carpentary_api),
    
    # re_path(r'polish-details',views.polish_details),
    # re_path(r'polish-assign/(?P<pk>.*)/$',views.assign_polish_api),
    
    # re_path(r'glass-details',views.glass_details),
    # re_path(r'glass-assign/(?P<pk>.*)/$',views.assign_glass_api),
    
    # re_path(r'packing-details',views.packing_details),
    # re_path(r'packing-assign/(?P<pk>.*)/$',views.assign_packing_api),

    re_path(r'color-create/',views.color_create),
    re_path(r'color-delete/(?P<pk>.*)/$',views.color_delete),
    re_path(r'color-list/',views.color_list),

    re_path(r'size-list/',views.size_list),
    re_path(r'size-create/',views.size_create),
    re_path(r'size-delete/(?P<pk>.*)/$',views.size_delete),

    re_path(r'model-list/',views.modelnumberbasedproducts_list),
    re_path(r'model-delete/(?P<pk>.*)/$',views.modelnumberbasedproducts_delete),
    re_path(r'model-create/',views.modelnumberbasedproducts_create),
    re_path(r'model-update/(?P<pk>.*)/$',views.modelnumberbasedproducts_update),
    re_path(r'model-info/(?P<pk>.*)/$',views.modelnumberbasedproducts_detail),

    re_path(r'work-order-image-create/(?P<pk>.*)/$',views.create_work_order_image),
]

core/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import  include, path, re_path
from core import settings
from main import views as general_views

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),   
    
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/',general_views.app,name='app'),
    path('',include(('main.urls'),namespace='main')), 
    path('settings/', include('settings.urls', namespace='settings')),
    path('workorder/',include('work_order.urls',namespace='workorder')),
    
    # admin panel
    path('super-admin/product/',include(('product.urls'),namespace='product')),
    path('staff/', include('staff.urls', namespace='staff')),
    
    # api
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include(('api.v1.authentication.urls','authentication'), namespace='api_v1_authentication')),
    path('api/v1/product/', include(('api.v1.product.urls','product'), namespace='api_v1_product')),
    path('api/v1/work-order/', include(('api.v1.work_order.urls','work_order'), namespace='api_v1_work_order')),
    path('api/v1/customer/',include(('api.v1.customers.urls','customer'),namespace='customer')),
    path('api/v1/staff/',include(('api.v1.staff.urls','customer'),namespace='staff')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

work_order/urls.py
from django.urls import path,re_path
from . import views

app_name = 'work_order'

urlpatterns = [
    path('color-autocomplete/', views.ColorAutocomplete.as_view(), name='color_autocomplete'),
    
    re_path(r'work-order-info/(?P<pk>.*)/$', views.work_order_info, name='work_order_info'),
    re_path(r'work-order-list/$', views.work_order_list, name='work_order_list'),
    re_path(r'create-work-order/$', views.create_work_order, name='create_work_order'),
    re_path(r'edit-work-order/(?P<pk>.*)/$', views.edit_work_order, name='edit_work_order'),
    re_path(r'delete-work-order/(?P<pk>.*)/$', views.delete_work_order, name='delete_work_order'),
    re_path(r'delete-work-order-image/(?P<pk>.*)/$', views.delete_work_order_image, name='delete_work_order_image'),
    re_path(r'assign-work-order/$', views.assign_work_order, name='assign_work_order'),
    re_path(r'fetch-customer-details/$', views.fetch_customer_details, name='fetch_customer_details'),
    re_path(r'profit-loss/(?P<pk>.*)/$', views.profit_loss, name='profit_loss'),

    #-----------------Wood Section---------------------
    re_path(r'^wood_work_orders_list/', views.wood_work_orders_list, name='wood_work_orders_list'),
    re_path(r'^assign_wood/(?P<pk>.*)/$', views.assign_wood, name='assign_wood'),
    re_path(r'^allocated_wood/(?P<pk>.*)/$', views.allocated_wood, name='allocated_wood'),
    re_path(r'^edit_wood_assignment/(?P<pk>.*)/$', views.edit_wood_assignment, name='edit_wood_assignment'),
    # path("work-order/<int:pk>/edit-wood-assignment/", views.edit_wood_assignment, name="edit_wood_assignment"),

    #-----------------Carpentary--------------------------
    re_path(r'^carpentary_list/', views.carpentary_list, name='carpentary_list'),
    re_path(r'^assign_carpentary/(?P<pk>.*)/$', views.assign_carpentary, name='assign_carpentary'),
    re_path(r'^allocated_carpentary/(?P<pk>.*)/$', views.allocated_carpentary, name='allocated_carpentary'),
    re_path(r'^edit_carpentary_assignment/(?P<pk>.*)/$', views.edit_carpentary_assignment, name='edit_carpentary_assignment'),

    #-----------------Polish--------------------------
    re_path(r'^polish_list/', views.polish_list, name='polish_list'),
    re_path(r'^assign_polish/(?P<pk>.*)/$', views.assign_polish, name='assign_polish'),
    re_path(r'^allocated_polish/(?P<pk>.*)/$', views.allocated_polish, name='allocated_polish'),
    re_path(r'^edit_polish_assignment/(?P<pk>.*)/$', views.edit_polish_assignment, name='edit_polish_assignment'),
    
    #-------------Glass/Upholstory-------------------------------------------------------
    re_path(r'^glass_list/', views.glass_list, name='glass_list'),
    re_path(r'^assign_glass/(?P<pk>.*)/$', views.assign_glass, name='assign_glass'),
    re_path(r'^allocated_glass/(?P<pk>.*)/$', views.allocated_glass, name='allocated_glass'),
    re_path(r'^edit_glass_assignment/(?P<pk>.*)/$', views.edit_glass_assignment, name='edit_glass_assignment'),
    #-------------Packing-------------------------------------------------------
    re_path(r'^packing_list/', views.packing_list, name='packing_list'),
    re_path(r'^assign_packing/(?P<pk>.*)/$', views.assign_packing, name='assign_packing'),
    re_path(r'^allocated_packing/(?P<pk>.*)/$', views.allocated_packing, name='allocated_packing'),
    re_path(r'^edit_packing_assignment/(?P<pk>.*)/$', views.edit_packing_assignment, name='edit_packing_assignment'),
    #--------- staff assigning for various work sections---------------------
    re_path(r'^wood_order_staff_assign/(?P<pk>.*)/$',views.wood_order_staff_assign,name='wood-order-staff-assign'),
    re_path(r'^carpentar_order_staff_assign/(?P<pk>.*)/$',views.carpentary_order_staff_assign,name='carpentar_order_staff_assign'),
    re_path(r'polish_order_staff_assign/(?P<pk>.*)/$',views.polish_order_staff_assign,name='polish_order_staff_assign'),
    re_path(r'glass_order_staff_assign/(?P<pk>.*)/$',views.glass_order_staff_assign,name='glass_order_staff_assign'),
    re_path(r'packing_order_staff_assign/(?P<pk>.*)/$',views.packing_order_staff_assign,name='packing_order_staff_assign'),
    
    re_path(r'^create_color/$', views.create_color, name='create_color'), 
    re_path(r'^color_list/$', views.color_list, name='color_list'),
    re_path(r'^delete_color/(?P<pk>.*)/$', views.delete_color, name='delete_color'),

    re_path(r'size-create/',views.size_create,name='size-create'),
    re_path(r'size-list/',views.size_list,name='size-list'),
    re_path(r'^delete-size/(?P<pk>.*)/$', views.size_delete, name='size-delete'),

    # re_path(r'model-list/',views.modelnumberbasedproducts_list,name='model-list'),
    re_path(r'model-create/',views.modelnumberbasedproducts_create,name='model-create'),
    re_path(r'model-edit/(?P<pk>.*)/$',views.modelnumberbasedproducts_update,name='model-edit'),
    re_path(r'model-delete/(?P<pk>.*)/$',views.modelnumberbasedproducts_delete,name='model-delete'),
    re_path(r'model-info/(?P<pk>.*)/$',views.modelnumberbasedproducts_info,name='model-info'),
    re_path(r'model-data/',views.get_model_details,name='model-data'),

    re_path(r'model-display/',views.modelnumberbasedproducts_card_list,name='model-display'),
    re_path(r'get-subcategories/',views.get_subcategories, name='get-subcategories'),

    re_path(r'get-subcategory/', views.get_subcategory, name='get-subcategory'),
    re_path(r'get-sub-materials/', views.get_sub_materials, name='get-sub-materials'),
    re_path(r'get-material-types/', views.get_material_types, name='get-material-types'),

    re_path(r'delete-model-image/(?P<pk>.*)/$',views.delete_model_image,name='delete-model-image'),
    re_path(r'delete-orders/',views.delete_orders,name='delete-orders'),
    
    # reports
    re_path(r'delayed-work-orders/',views.delayed_work_order_report,name='delayed_work_order_report'),
    re_path(r'print-delayed-work-orders/',views.print_delayed_work_order_report,name='print_delayed_work_order_report'),
    re_path(r'export-delayed-work-orders/',views.export_delayed_work_orders_excel,name='export_delayed_work_orders_excel'),

    path('work-orders-summary/', views.work_summary, name='work_summary'),
    path('print-work-summary-orders/',views.print_work_summary_report,name='print_work_summary_report'),
    path('export-work-orders-summary/', views.export_work_orders_summary_excel, name='export_work_orders_summary_excel'),
    
    path('accessories-utilized/', views.accessories_utilized, name='accessories_utilized'),
    path('wood-conseption-report/', views.wood_conseption_report, name='wood_conseption_report'),
    path('print-accessories-utilized/', views.print_accessories_utilized, name='print_accessories_utilized'),
    path('export-accessories-utilized/', views.export_accessories_utilized, name='export_accessories_utilized'),

    path('work-report/', views.work_report, name='work_report'),
    path("staff-work-order-details/<uuid:staff_id>/", views.staff_work_detail, name="staff_work_detail"),
    path('print-work-report/', views.print_work_report, name='print_work_report'),
    path('export-work-report/', views.export_work_report_excel, name='export_work_report_excel'),
    
    path('work-order-used-accessories-report/', views.work_order_used_accessories_report, name='work_order_used_accessories_report'),
    path('print-work-order-used-accessories-report/', views.print_work_order_used_accessories_report, name='print_work_order_used_accessories_report'),
    path('export-work-order-used-accessories-report/', views.export_work_order_used_accessories_report, name='export_work_order_used_accessories_report'),
    
    path('production-cost-wo-list/', views.production_cost_wo_list, name='production_cost_wo_list'),
    path('production-cost-wo-print/', views.production_cost_wo_print, name='production_cost_wo_print'),
    path('production-cost-wo-export/', views.production_cost_wo_export, name='production_cost_wo_export'),
    path("work-order/<uuid:pk>/profit-loss/", views.work_order_profit_loss_view, name="work_order_profit_loss"),
    path("work-order/<uuid:pk>/profit-loss-print/", views.work_order_profit_loss_print, name="work_order_profit_loss_print"),
    path("work-order/<uuid:pk>/profit-loss-export/", views.work_order_profit_loss_export, name="work_order_profit_loss_export"),
    path('labour-detail/<uuid:pk>/', views.work_order_labour_detail_view, name='work_order_labour_detail'),
    path('labour-detail/print/<uuid:pk>/', views.work_order_labour_detail_print, name='work_order_labour_detail_print'),
    path('labour-detail/export/<uuid:pk>/', views.work_order_labour_detail_export, name='work_order_labour_detail_export'),
    path('work-order/<uuid:pk>/accessories-detail/', views.production_cost_wo_used_accessories_detail, name='production_cost_wo_used_accessories_detail'),
    path('work-order/<uuid:pk>/accessories-print/', views.production_cost_wo_used_accessories_print, name='production_cost_wo_used_accessories_print'),
    path('work-order/<uuid:pk>/accessories-excel/', views.production_cost_wo_used_accessories_excel, name='production_cost_wo_used_accessories_excel'),

     path(
        'items/<uuid:pk>/',
        views.work_order_items,
        name='work_order_items'
    ),

    path('units/', views.unit_list, name='unit_list'),
    path('units/create/', views.unit_create, name='unit_create'),


]

templates/admin_panel/pages/work_order/order/list.html
{% extends 'admin_panel/base.html' %}
{% load static %}
{% load work_order_templatetags %}
{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col-lg-8">
                                <h4 class="page-title">{{page_title}}</h4>
                            </div><!--end col-->
                            <div class="col-lg-4 col-sm-2 float-right ml-auto">
                                <form method="get" action="">
                                    <li class="list-inline-item w-100">
                                        <div class="input-group">
                                            <input name="q" type="text" id="search_box" placeholder="Order No. or Customer" value="{{ filter_data.q }}"
                                                class="form-control" />
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-soft-primary btn-sm"><i class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex">
                            <div class="col-lg-4">
                                <h4 class="card-title">List view</h4>
                            </div>
                            {% comment %} <div class="col-md-8 text-right">
                                <a href="javascript:void('0');" id="print_button" class="btn btn-light text-capitalize border-0 ripple-surface-dark" style="color:#000"><i class="ri-printer-line text-primary" style="color:#3f51b5;"></i> Print</a>
                                <a href="javascript:void('0');" id="export_button" class="btn btn-light text-capitalize border-0 ripple-surface-dark" style="color:#000"><i class="ri-file-excel-2-line text-danger"></i> Export</a>
                                <div class="dropdown" style="display: inline;width: max-content;">
                                    <button class="btn btn-info dropdown-toggle" type="button" id="filterMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="ri-filter-fill"></i> Filter
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterMenuButton">
                                        <form action="." method="GET" class="px-4 py-3">
                                            <div class="form-group">
                                                <label for="inputField">Select Date</label>
                                                <input type="text" id="reportrange" class="form-control" name="date_range" value="{% if not filter_data.date_range %}{{first_date_formatted}} - {{last_date_formatted}}{% else %}{{filter_data.date_range}}{% endif %}" style="display: inline;width: max-content;">
                                            </div>
                                            <div class="form-group">
                                                <label for="inputField">Branch</label>
                                                <select class="form-control" name="branch">
                                                </select>
                                            </div>
                                            <div class="form-group">
                                                <label for="radioButtons">Distribution Center</label>
                                                <select class="form-control" name="distribution">
                                                </select>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Apply</button>
                                      </form>
                                    </div>
                                </div>
                            </div> {% endcomment %}
                        </div>
                        <!--end card-header-->
                        <form method="post" action="{% url 'work_order:delete-orders' %}" id="delete-orders-form">
                            {% csrf_token %}
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0" style="">
                                    <thead>
                                        <tr>
                                            <th class="font-weight-bold text-center">#</th>
                                            <th></th>
                                            <th class="font-weight-bold text-center">Date Added</th>
                                            <th class="font-weight-bold text-left">Order No</th>
                                            <th class="font-weight-bold text-left">Customer Name</th>
                                            <th class="font-weight-bold text-center">Delivery Date</th>
                                            <th class="font-weight-bold text-center">Status</th>
                                            <th class="font-weight-bold text-right">Total Estimate</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 10 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td class="text-center">{{forloop.counter}}</td>
                                            <td><input type="checkbox" name="order_ids" value="{{ instance.id}}"></td>
                                            <td class="text-center">{{instance.date_added|date:"d/m/Y"}}</td>
                                            <td class="text-left">{{instance.order_no}}</td>
                                            <td class="text-left">{{instance.customer.name}}</td>
                                            <td class="text-center">{{instance.delivery_date|date:"d/m/Y"}}</td>
                                            <td class="text-center">{{instance.get_status_display}}</td>
                                            <td class="text-right">{{instance.total_estimate}}</td>
                                            
                                            <td class="text-right">
                                            <a href="javascript: void(0);" data-bs-toggle="modal" data-bs-target="#WorkAssignModal" data-unique_id="{{ instance.pk }}" onclick="handleButtonClick(this)" title="Assign Work">
                                                <i class="las la-people-carry text-warning font-18"></i>
                                            </a>
                                            <a href="{% url 'work_order:work_order_info' pk=instance.pk %}" title="View Details">
                                                <i class="las la-eye text-success font-18"></i>
                                            </a>
                                            <a href="{% url 'work_order:edit_work_order' pk=instance.pk %}" title="Edit Work Order">
                                                <i class="las la-pen text-info font-18"></i>
                                            </a>
                                            <a href="{% url 'work_order:profit_loss' pk=instance.pk %}" title="Profit & Loss">
                                                <i class="las la-chart-line text-primary font-18"></i>
                                            </a>
                                            <a data-id="{{ instance.pk }}" data-text="{{ confirm_delete_message }}" data-title="Are you sure?" href="{% url 'work_order:delete_work_order' pk=instance.pk %}" title="Delete Work Order">
                                                <i class="las la-trash-alt text-danger font-18"></i>
                                            </a>
                                        </td>

                                        </tr>
                                        {% endfor %}

                                    </tbody>
                                </table>
                                <button class="btn btn-outline-danger" type="button" onclick="submitDeleteForm()">Delete Selected Orders</button>
                            </form>
                                <!--end /table-->
                                {% get_pages %}
                                <div class="clearfix"></div>
                                <div class="row pagi my-3">
                                    <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                                    <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                        <div class="m-t-10">
                                            Showing {{title}}
                                            <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                                class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                                class="total_count">{{ pages.total_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->

        <!-- Modal -->
        <div class="modal fade" id="WorkAssignModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Assign Section</h5>
                    <button type="button" class="btn-close text-dark" data-bs-dismiss="modal" aria-label="Close" onclick="clearForm()">
                      <span aria-hidden="true">×</span>
                    </button>
                  </div>
                  <form action="{% url 'work_order:assign_work_order' %}" method="POST" enctype="multipart/form-data" class="ajax redirect">
                      <div class="modal-body">
                          {% csrf_token %}
                          {% work_order_status_assign_form as workstatusassignform %}
                          <input type="hidden" name="order_id" class="form-control" id="orderIdModalField">
                          <div class="form-group">
                              <label for="recipient-name" class="col-form-label">Status:</label>
                              {{workstatusassignform.to_section}}
                          </div>
                          <div class="form-group">
                              <label for="message-text" class="col-form-label">Remark:</label>
                              {{workstatusassignform.description}}
                          </div>
                      </div>
                      <div class="modal-footer">
                          <button type="submit" class="btn bg-gradient-primary" >Submit</button>
                      </div>
                  </form>
                </div>
              </div>
        </div>
        
    <!-- end page content -->
{% endblock content %}


{% block static %}
{% load static %}
<script>
    function handleButtonClick(button) {
        $('#WorkAssignModal').modal('show');
        var orderId = $(button).attr("data-unique_id");
        $("#orderIdModalField").val(orderId);
    };
    function clearForm() {
        // Clear the form fields
        document.getElementById('orderIdModalField').value = '';
        document.getElementById('id_to_section').value = '';
        document.getElementById('id_description').value = '';
        $('#WorkAssignModal').modal('hide');
      }
</script>

<script>
    function submitDeleteForm() {
        const form = document.getElementById('delete-orders-form');
        const formData = new FormData(form);
        const selectedOrders = formData.getAll('order_ids');

        if (selectedOrders.length === 0) {
            alert('No orders selected for deletion.');
            return;
        }

        // Confirm deletion
        if (confirm('Are you sure you want to delete the selected orders?')) {
            form.submit();
        }
    }
</script>

{% endblock static %}
    
        