api/v1/product/urls.py
from django.urls import path, re_path
from . import views

app_name = 'api_v1_product'

urlpatterns = [
    re_path(r'^materials/$', views.materials),
    re_path(r'^product-category/$', views.product_category),
    re_path(r'product-details', views.get_product),
]

core/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import  include, path, re_path
from core import settings
from main import views as general_views

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),   
    
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/',general_views.app,name='app'),
    path('',include(('main.urls'),namespace='main')), 
    path('settings/', include('settings.urls', namespace='settings')),
    path('workorder/',include('work_order.urls',namespace='workorder')),
    
    # admin panel
    path('super-admin/product/',include(('product.urls'),namespace='product')),
    path('staff/', include('staff.urls', namespace='staff')),
    
    # api
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include(('api.v1.authentication.urls','authentication'), namespace='api_v1_authentication')),
    path('api/v1/product/', include(('api.v1.product.urls','product'), namespace='api_v1_product')),
    path('api/v1/work-order/', include(('api.v1.work_order.urls','work_order'), namespace='api_v1_work_order')),
    path('api/v1/customer/',include(('api.v1.customers.urls','customer'),namespace='customer')),
    path('api/v1/staff/',include(('api.v1.staff.urls','customer'),namespace='staff')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

product/urls.py
from django.urls import path,re_path
from . import views

app_name = 'product'

urlpatterns = [
    re_path(r'get-sub-category/$', views.get_sub_category, name='get_sub_category'),
    re_path(r'get-materials-type/$', views.get_materials_type, name='get_materials_type'),
    re_path(r'get-materials-type-category/$', views.get_materials_type_category, name='get_materials_type_category'),
    
    re_path(r'material-info/(?P<pk>.*)/$', views.material_info, name='material_info'),
    re_path(r'material-list/$', views.material_list, name='material_list'),
    re_path(r'create-material/$', views.create_material, name='create_material'),
    re_path(r'edit-material/(?P<pk>.*)/$', views.edit_material, name='edit_material'),
    re_path(r'delete-material/(?P<pk>.*)/$', views.delete_material, name='delete_material'),
    
    re_path(r'product-category-list/$', views.product_category_list, name='product_category_list'),
    re_path(r'create-product-category/$', views.create_product_category, name='create_product_category'),
    re_path(r'edit-product-category/(?P<pk>.*)/$', views.edit_product_category, name='edit_product_category'),
    re_path(r'delete-product-category/(?P<pk>.*)/$', views.delete_product_category, name='delete_product_category'),
    
    re_path(r'product-info/(?P<pk>.*)/$', views.product_info, name='product_info'),
    re_path(r'product-list/$', views.product_list, name='product_list'),
    re_path(r'create-product/$', views.create_product, name='create_product'),
    re_path(r'edit-product/(?P<pk>.*)/$', views.edit_product, name='edit_product'),
    re_path(r'delete-product/(?P<pk>.*)/$', views.delete_product, name='delete_product'),
    re_path(r'delete-product-image/(?P<pk>.*)/$', views.delete_product_image, name='delete_product_image'),
]

product/models.py
#django
from django.db import models
#third party
from ckeditor_uploader.fields import RichTextUploadingField
from versatileimagefield.fields import VersatileImageField
#local
from main.models import BaseModel

# Create your models here.
PRODUCT_SOURCE_CHOICES = (
    ('010', 'Own Product'),
    ('015', 'Trading'),
)

class Materials(BaseModel):
    name = models.CharField(max_length=200)
    is_subcategory = models.BooleanField(default=False)
    image = VersatileImageField('Image', upload_to="product/material", blank=True, null=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    class Meta:
        db_table = 'product_material'
        verbose_name = ('Product Material')
        verbose_name_plural = ('Product Material')
        
    def __str__(self):
        return f'{self.name}'
    
    def material_types(self):
        return MaterialsType.objects.filter(is_deleted=False,material=self)
        
  
class MaterialsType(BaseModel):
    name = models.CharField(max_length=200)
    material = models.ForeignKey(Materials, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    is_subcategory = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'product_material_type'
        verbose_name = ('Product Material Type')
        verbose_name_plural = ('Product Material Type')
        
    def __str__(self):
        return f'{self.name}'
    
    def subcategories_joint(self):
        categories = MaterialTypeCategory.objects.filter(is_deleted=False,material_type=self)
        if categories:
            return ','.join(category.name for category in categories)
        else:
            return ""
        
    def subcategories_list(self):
        return MaterialTypeCategory.objects.filter(is_deleted=False,material_type=self)
    
    
class MaterialTypeCategory(BaseModel):
    name = models.CharField(max_length=200)
    material_type = models.ForeignKey(MaterialsType, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    
    class Meta:
        db_table = 'product_material_type_category'
        verbose_name = ('Product Material Type Category')
        verbose_name_plural = ('Product Material Type Category')
        
    def __str__(self):
        return f'{self.name}'
    

class ProductCategory(BaseModel):
    name = models.CharField(max_length=200)
    is_subcategory = models.BooleanField(default=False)
    image = VersatileImageField('Image', upload_to="product/material", blank=True, null=True)
    
    class Meta:
        db_table = 'product_category'
        verbose_name = ('Product Category')
        verbose_name_plural = ('Product Category')
        
    def __str__(self):
        return f'{self.name}'
    
    def subcategories_list(self):
        return ProductSubCategory.objects.filter(is_deleted=False,product_category=self)
   
    
class ProductSubCategory(BaseModel):
    name = models.CharField(max_length=200)
    product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    
    class Meta:
        db_table = 'product_sub_category'
        verbose_name = ('Product Sub Category')
        verbose_name_plural = ('Product Sub Category')
        
    def __str__(self):
        return f'{self.name}'
    

class Product(BaseModel):
    name = models.CharField(max_length=200)
    color = models.CharField(max_length=100)
    item_code = models.CharField(max_length=100)
    source = models.CharField(max_length=10, choices=PRODUCT_SOURCE_CHOICES)
    approximate_development_time = models.DecimalField(default=0,max_digits=10,decimal_places=2)
    remark = RichTextUploadingField()
    feuture_image = VersatileImageField('Image', upload_to="product/feuture_image", blank=True, null=True)
    
    product_category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    product_sub_category = models.ForeignKey(ProductSubCategory, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False},null=True,blank=True)
    material = models.ForeignKey(Materials, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    material_type = models.ForeignKey(MaterialsType, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False},null=True,blank=True)
    material_type_category = models.ForeignKey(MaterialTypeCategory, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False},null=True,blank=True)
    
    class Meta:
        db_table = 'product_product'
        verbose_name = ('Product')
        verbose_name_plural = ('Product')
        
    def __str__(self):
        return f'{self.name}'
    
    
class ProductImage(BaseModel):
    image = VersatileImageField('Image', upload_to="product/product_image")
    
    product = models.ForeignKey(Product, on_delete=models.CASCADE, limit_choices_to={'is_deleted': False})
    
    class Meta:
        db_table = 'product_product_image'
        verbose_name = ('Product Image')
        verbose_name_plural = ('Product Image')
        
    def __str__(self):
        return f'{self.product.name}'

product/forms.py
from datetime import date

from django import forms
from django.forms import formset_factory, inlineformset_factory
from django.forms.widgets import TextInput,Textarea,Select,DateInput,CheckboxInput,FileInput,PasswordInput

from . models import *


class MaterialsForm(forms.ModelForm):
    
    class Meta:
        model = Materials
        fields = ['name','is_subcategory','image','amount']

        widgets = {
            'name': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Material Name'}), 
            'image': FileInput(attrs={'class': 'form-control dropify'}),
            'amount': TextInput(attrs={'type': 'number', 'step': '0.01', 'class': 'form-control', 'placeholder': 'Enter Amount'})

        }
        

class MaterialsTypeForm(forms.ModelForm):
    sub_category_name = forms.CharField(max_length=150, required=False, widget=forms.TextInput(attrs={'type': 'text','class': 'required form-control type_sub_category_name','placeholder': 'Enter Material Type Sub Category Names'}))
    
    class Meta:
        model = MaterialsType
        fields = ['name','is_subcategory','sub_category_name']

        widgets = {
            'name': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Material Type Name'}), 
            'is_subcategory': CheckboxInput(attrs={'class': 'material_type_subcategory_checkbox'}), 
            'sub_category_name': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Sub Category Name'}), 
        }
        
    def __init__(self, *args, **kwargs):
        instance = kwargs.get('instance')
        super().__init__(*args, **kwargs)
        
        if instance and isinstance(instance, MaterialsType):
            self.fields['sub_category_name'].initial = instance.subcategories_joint()
        

class ProductCategoryForm(forms.ModelForm):
    
    class Meta:
        model = ProductCategory
        fields = ['name','is_subcategory','image']

        widgets = {
            'name': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Product Category Name'}), 
            'image': FileInput(attrs={'class': 'form-control dropify'}),
        }
        

class ProductSubCategoryForm(forms.ModelForm):
    
    class Meta:
        model = ProductSubCategory
        fields = ['name']

        widgets = {
            'name': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Product Sub Category Name'}), 
        }
        

class ProductForm(forms.ModelForm):
    source = forms.ChoiceField(widget=forms.RadioSelect,choices=PRODUCT_SOURCE_CHOICES)
    
    class Meta:
        model = Product
        fields = ['name','color','item_code','source','approximate_development_time','remark','feuture_image','product_category','product_sub_category','material','material_type','material_type_category']

        widgets = {
            'name': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Product Name'}), 
            'color': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Product Color'}), 
            'item_code': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Item Code'}), 
            'approximate_development_time': TextInput(attrs={'type':'text','class': 'required form-control','placeholder' : 'Enter Product Sub Category Name'}), 
            'feuture_image': FileInput(attrs={'class': 'form-control dropify'}),
            'product_category': Select(attrs={'class': 'select2 form-control custom-select'}),
            'product_sub_category': Select(attrs={'class': 'select2 form-control custom-select'}),
            'material': Select(attrs={'class': 'select2 form-control custom-select'}),
            'material_type': Select(attrs={'class': 'select2 form-control custom-select'}),
            'material_type_category':  Select(attrs={'class': 'select2 form-control custom-select'}),
        }
        

class ProductImageForm(forms.ModelForm):
    
    class Meta:
        model = ProductImage
        fields = ['image']

        widgets = {
            'image': FileInput(attrs={'class': 'form-control dropify'}),
        }

api/v1/product/views.py
import requests
from datetime import datetime

from django.utils.html import strip_tags
from django.db.models import Q,Sum,Min,Max 
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string

from rest_framework import status
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer
from rest_framework.authentication import BasicAuthentication
from rest_framework.decorators import api_view, permission_classes, renderer_classes
from rest_framework.permissions import AllowAny, IsAuthenticated,IsAuthenticatedOrReadOnly

from .serializers import *
from product.views import Product
from product.models import Materials, ProductCategory
from main.functions import decrypt_message, encrypt_message
from api.v1.product.serializers import MaterialsSerializer, ProductCategorySerializer
from api.v1.authentication.functions import generate_serializer_errors, get_user_token


@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def materials(request):
    if request.method == 'GET':
        section = request.GET.get("section")
        
        instances = Materials.objects.filter(is_deleted=False)
        
        if section:
            if section.lower() == "wood":
                instances = instances.filter(name__in=["Wood","wood"])
            else:
                instances = instances.filter(name__in=["Accessories","accessories"])
        
        serializer = MaterialsSerializer(instances,many=True)
        
        status_code = status.HTTP_200_OK
        response_data = {
            "StatusCode": 200,
            "status": status_code,
            "data": serializer.data,
        }
        
    return Response(response_data, status=status_code)

@api_view(['GET'])
@permission_classes((IsAuthenticated,))
@renderer_classes((JSONRenderer,))
def product_category(request):
    if request.method == 'GET':
        
        instances = ProductCategory.objects.filter(is_deleted=False)
        serializer = ProductCategorySerializer(instances,many=True)
        
        status_code = status.HTTP_200_OK
        response_data = {
            "StatusCode": 200,
            "status": status_code,
            "data": serializer.data,
        }
        
    return Response(response_data, status=status_code)

@api_view(['GET'])
def get_product(request,id=None):
    try:
        if id:
            queryset=Product.objects.get(id=id)
            serializer=ProductSerializer(queryset)
            return Response(serializer.data)
        queryset=Product.objects.all()
        serializer=ProductSerializer(queryset,many=True)
        return Response(serializer.data)
    except  Exception as e:
        print(e)
        return Response({'status': False, 'message': 'Something went wrong!'})

templates/admin_panel/pages/product/materials/info.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col">
                                <h4 class="page-title">{{page_title}}</h4>
   
                            </div><!--end col-->
                            
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->

            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex" style="background-color:#f8f9fa;">
                            <div class="col-md-6">
                                <strong> Material Name : {{ instance.name }}</strong><br>
                            </div>
                            <div class="col-md-6 text-right">
                                <a href="{% url 'product:edit_material' pk=instance.pk %}" class="btn btn-primary"><i class="las la-pen"></i> Edit</a>
                                <a href="{% url 'product:delete_material' pk=instance.pk %}" class="action-button remove redirect btn btn-danger" data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?"><i class="las la-trash-alt font-18"></i> Delete</a>
                            </div>
                        </div>
                        <div class="card-body p-0">
                            <div class="table-responsive-sm">
                                <table class="table table-striped mb-0" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th class="font-weight-bold text-center">#</th>
                                            <th class="font-weight-bold text-left">Item</th>
                                            <th class="font-weight-bold text-left">Sub Categories</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for type in instance.material_types.all %}
                                        <tr>
                                            <td class="text-center">{{forloop.counter}}</td>
                                            <td class="text-left">{{type.name}}</td>
                                            <td class="text-center">
                                                {% if type.subcategories_list %}
                                                <table class="table mb-0">
                                                    <thead>
                                                        <tr>
                                                            <th class="font-weight-bold text-center">#</th>
                                                            <th class="font-weight-bold text-left">Name</th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        {% for category in type.subcategories_list.all %}
                                                        <tr>
                                                            <td class="text-center">{{forloop.counter}}</td>
                                                            <td class="text-left">{{ category.name }}</td>
                                                        </tr>
                                                        {% endfor %}
                                                    </tbody>
                                                </table>
                                                {% else %}
                                                -
                                                {% endif %}
                                            </td>
                                        </tr>
                                        
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>

        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}


{% block static %}
{% load static %}
{{form.media}}

    
{% endblock static %}
    
        

templates/admin_panel/pages/product/materials/list.html
{% extends 'admin_panel/base.html' %}
{% load static %}
{% load main_templates_tags %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col-lg-8">
                                <h4 class="page-title">{{page_title}}</h4>
                            </div><!--end col-->
                            <div class="col-lg-4 col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'product:material_list' %}">
                                    <li class="list-inline-item w-100">
                                        <div class="input-group">
                                            <input name="q" type="text" id="search_box" placeholder="search" value="{{ filter_data.q }}"
                                                class="form-control" />
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-soft-primary btn-sm"><i class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex">
                            <div class="col-lg-4">
                                <h4 class="card-title">List view</h4>
                            </div>
                            <div class="col-md-8 text-right">
                                {% comment %} <a href="javascript:void('0');" id="print_button" class="btn btn-light text-capitalize border-0 ripple-surface-dark" style="color:#000"><i class="ri-printer-line text-primary" style="color:#3f51b5;"></i> Print</a>
                                <a href="javascript:void('0');" id="export_button" class="btn btn-light text-capitalize border-0 ripple-surface-dark" style="color:#000"><i class="ri-file-excel-2-line text-danger"></i> Export</a> {% endcomment %}
                                <div class="dropdown" style="display: inline;width: max-content;">
                                    <button class="btn btn-info dropdown-toggle" type="button" id="filterMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="ri-filter-fill"></i> Filter
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterMenuButton">
                                        <form action="." method="GET" class="px-4 py-3">
                                            <div class="form-group">
                                                <label for="inputField">Select Date</label>
                                                <input type="text" id="reportrange" class="form-control" name="date_range" value="{% if not filter_data.date_range %}{{first_date_formatted}} - {{last_date_formatted}}{% else %}{{filter_data.date_range}}{% endif %}" style="display: inline;width: max-content;">
                                            </div>
                                            <div class="form-group">
                                                <label for="inputField">Branch</label>
                                                {% comment %} <select class="form-control" name="branch">
                                                    {% get_branches as branches %}
                                                    <option value="">All</option>
                                                    {% for branch in branches %}
                                                    <option value="{{branch.pk}}" {% if filter_data.branch|stringformat:"s" == branch.pk|stringformat:"s" %}selected{% endif %}>{{branch.name}}</option>
                                                    {% endfor %}
                                                </select> {% endcomment %}
                                            </div>
                                            <div class="form-group">
                                                <label for="radioButtons">Distribution Center</label>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Apply</button>
                                      </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th class="font-weight-bold text-center">#</th>
                                            <th class="font-weight-bold text-left">Name</th>
                                            <th class="font-weight-bold text-center">Sub Category</th>
                                            <th class="font-weight-bold text-right">Image</th>
                                            <th class="font-weight-bold text-right">Cost</th>
                                            <th class="text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 10 instances %}
                                        {% for instance in instances %}
                                        <tr>
                                            <td class="text-center">{{forloop.counter}}</td>
                                            <td class="text-left">{{instance.name}}</td>
                                            <td class="text-center">{{instance.is_subcategory}}</td>
                                            <td class="text-center">{% if instance.image %}{{instance.image.url}}{% endif %}</td>
                                            <td class="text-center">{{instance.amount}}</td>
                                            <td class="text-right">
                                                <a href="{% url 'product:material_info' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a>
                                                <a href="{% url 'product:edit_material' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a href="{% url 'product:delete_material' pk=instance.pk %}" class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?"><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--end /table-->
                                {% get_pages %}
                                <div class="clearfix"></div>
                                <div class="row pagi my-3">
                                    <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                                    <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                        <div class="m-t-10">
                                            Showing {{title}}
                                            <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                                class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                                class="total_count">{{ pages.total_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}


{% block static %}
{% load static %}


{% endblock static %}
    
        