core/urls.py
from django.contrib import admin
from django.views.static import serve
from django.urls import  include, path, re_path
from core import settings
from main import views as general_views

urlpatterns = [
    path('ckeditor/', include('ckeditor_uploader.urls')),   
    
    path('admin/', admin.site.urls),
    path('app/accounts/', include('registration.backends.default.urls')),
    path('super-admin/',general_views.app,name='app'),
    path('',include(('main.urls'),namespace='main')), 
    path('settings/', include('settings.urls', namespace='settings')),
    path('workorder/',include('work_order.urls',namespace='workorder')),
    
    # admin panel
    path('super-admin/product/',include(('product.urls'),namespace='product')),
    path('staff/', include('staff.urls', namespace='staff')),
    
    # api
    path('api-auth/', include('rest_framework.urls')),
    path('api/v1/auth/', include(('api.v1.authentication.urls','authentication'), namespace='api_v1_authentication')),
    path('api/v1/product/', include(('api.v1.product.urls','product'), namespace='api_v1_product')),
    path('api/v1/work-order/', include(('api.v1.work_order.urls','work_order'), namespace='api_v1_work_order')),
    path('api/v1/customer/',include(('api.v1.customers.urls','customer'),namespace='customer')),
    path('api/v1/staff/',include(('api.v1.staff.urls','customer'),namespace='staff')),

    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
]

staff/urls.py
from django.urls import re_path
from . import views

app_name = 'staff'

urlpatterns = [
    # Tile URL patterns
    re_path(r'^tile_info/(?P<pk>.*)/$', views.tile_info, name='tile_info'),
    re_path(r'^tile_list/$', views.tile_list, name='tile_list'),
    re_path(r'^tile_create/$', views.tile_create, name='tile_create'),
    re_path(r'^tile_edit/(?P<pk>.*)/$', views.tile_edit, name='tile_edit'),
    re_path(r'^tile_delete/(?P<pk>.*)/$', views.tile_delete, name='tile_delete'),
    
    re_path(r'^department_info/(?P<pk>.*)/$', views.department_info, name='department_info'),
    re_path(r'^department_list/$', views.department_list, name='department_list'),
    re_path(r'^department_create/$', views.department_create, name='department_create'),
    re_path(r'^department_edit/(?P<pk>.*)/$', views.department_edit, name='department_edit'),
    re_path(r'^department_delete/(?P<pk>.*)/$', views.department_delete, name='department_delete'),

    # Destination URL patterns
    re_path(r'^designation_info/(?P<pk>.*)/$', views.designation_info, name='designation_info'),
    re_path(r'^designation_list/$', views.designation_list, name='designation_list'),
    re_path(r'^designation_create/$', views.designation_create, name='designation_create'),
    re_path(r'^designation_edit/(?P<pk>.*)/$', views.designation_edit, name='designation_edit'),
    re_path(r'^designation_delete/(?P<pk>.*)/$', views.designation_delete, name='designation_delete'),
    
    #-------------------------------Staff-------------------------
    re_path(r'staff_info/(?P<pk>.*)/$', views.staff_info, name='staff_info'),
    re_path(r'staff_list/$', views.staff_list, name='staff_list'),
    re_path(r'staff_create/$', views.staff_create, name='staff_create'),
    re_path(r'staff_edit/(?P<pk>.*)/$', views.staff_edit, name='staff_edit'),
    re_path(r'staff_delete/(?P<pk>.*)/$', views.staff_delete, name='staff_delete'),
    
    #------------------------------- Attendence -------------------------
    re_path(r'attendence_list/$', views.attendence_list, name='attendence_list'),
    re_path(r'attendence_create/$', views.attendence_create, name='attendence_create'),
    re_path(r'attendence_edit/(?P<pk>.*)/$', views.attendence_edit, name='attendence_edit'),
    re_path(r'attendance_delete/(?P<pk>.*)/$', views.attendance_delete, name='attendance_delete'),
    
    re_path(r'get_staffs', views.get_staffs, name='get_staffs'),
    re_path(r'add_staff_to_list', views.add_staff_to_list, name='add_staff_to_list'),
    re_path(r'adding_attendence', views.adding_attendence, name='adding_attendence'),
]

templates/admin_panel/pages/attendence/attendence_create.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<!-- Page Content -->
<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">{{ page_title }}</h4>
                        </div><!-- end col -->
                    </div><!-- end row -->
                </div><!-- end page-title-box -->
            </div><!-- end col -->
        </div><!-- end row -->
        <!-- end page title end breadcrumb -->

        <form action="{{ url }}" method="POST" class="ajax redirect">
            <div class="row">
                <div class="col-12">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body bootstrap-select-1">


                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <!-- <label for="name"> Search Name </label> -->
                                        <input class="form-control" type="text" name="inp_name" id="inp_id" placeholder="search name">
                                    </div><!-- end form-group -->
                                </div><!-- end col -->

                                <div class="col-md-1">
                                    <div class="form-group">
                                        <input type="button" onclick="get_sttaff_names();" value="Search" class="form-control">
                                    </div><!-- end form-group -->
                                </div><!-- end col -->

                            </div><!-- end row -->
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <select id="search_id" class="form-control" name="search_name">
                                            <option value=""> ----- select ----- </option>
                                        </select>
                                    </div><!-- end form-group -->
                                </div><!-- end col -->

                                <div class="col-md-1">
                                    <div class="form-group">
                                        <input type="button" onclick="add_staff_list();" value="Submit" class="form-control">
                                    </div><!-- end form-group -->
                                </div><!-- end col -->

                            </div>
                        </div><!-- end card-body -->
                    </div><!-- end card -->

                    <!-- list  -->
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table mb-0" style="width:100%;">
                                <thead>
                                    <tr>
                                        <th class="font-weight-bold text-center">#</th>
                                        <th class="font-weight-bold text-left">Staff</th>
                                        <th class="font-weight-bold text-right">Select</th>
                                    </tr>
                                </thead>
                                <tbody id="list_tab_body" name="name_tab_body">
                                </tbody>
                            </table>
                            <!--end /table-->
                        </div>
                        <!--end /tableresponsive-->
                        <!-- pagination -->
                    <div class="mt-5"></div>
                    <button type="submit" id="submit" class="btn btn-soft-primary btn-sm waves-effect waves-light" >Save Changes</button>
                    <button type="button" onclick="window.history.back()" class="btn btn-soft-danger btn-sm">Cancel</button>
                </div><!-- end col -->
            </div><!-- end row -->
        </form><!-- end form -->
    </div><!-- container -->
</div><!-- end page content -->
{% endblock content %}

{% block static %}
{% load static %}
<!-- Additional styles if necessary -->
{{ form.media }}
<style>
    .form-group {
        margin-bottom: 10px;
    }
    .form-control {
        height: calc(2.8em + .75rem + 2px);
    }
</style>


<script>
    function get_sttaff_names()
    {
    var name = document.getElementById('inp_id').value
    $.ajax({
        type:'GET',
        url: 'get_staffs',
        data:{input_name : name},
        datatype:'json',
        success:function(data)
        {
            console.log(data);
            $('#search_id').find('option').remove();
              $.each(data.names, function(i=1, value) {
                $('#search_id').append('<option value="'+ value.auto_id +'">'+ value.first_name + ' ' + value.last_name + '</option>');
                });
        },
        });
    }

    function add_staff_list()
    {
    var drop_name = document.getElementById('search_id').value
    $.ajax({
        type:'GET',
        url: 'add_staff_to_list',
        data:{input_name : drop_name},
        datatype:'json',
        success:function(data)
        {
            console.log(data);
            $.each(data.names_list, function(i=1, value) {
                let row = `
                    <tr>
                        <td class="text-left">${value.first_name} ${value.last_name}</td>
                        <td class="text-left">
                            <input type="checkbox" class="form-control" name="staff_checkbox" value="${value.auto_id}">
                        </td>
                    </tr>`;
                $('#list_tab_body').append(row);
        });
        },
        });
    }

    function submitCheckedItems() {
        let checkedItems = [];
        $("input[name='staff_checkbox']:checked").each(function() {
            checkedItems.push($(this).val());
        });
        console.log("aaaaaaaaaaa"+checkedItems)
    
        $.ajax({
            type: 'GET',
            url: 'adding_attendence',
            data: {'checked_items': checkedItems},
            datatype:'json',
            success:function(data)
            {
                console.log(data);
            },
        });
    }
</script>

{% endblock %}

templates/admin_panel/pages/attendence/attendence_edit.html
{% extends 'admin_panel/base.html' %}
{% load static %}

{% block content %}
<!-- Page Content -->
<div class="page-content">
    <div class="container-fluid">
        <!-- Page-Title -->
        <div class="row">
            <div class="col-sm-12">
                <div class="page-title-box">
                    <div class="row">
                        <div class="col">
                            <h4 class="page-title">{{ page_title }}</h4>
                        </div><!-- end col -->
                    </div><!-- end row -->
                </div><!-- end page-title-box -->
            </div><!-- end col -->
        </div><!-- end row -->
        <!-- end page title end breadcrumb -->

        <form action="{{ url }}" method="POST" class="ajax redirect">
            <div class="row">
                <div class="col-12">
                    {% csrf_token %}
                    <div class="card">
                        <div class="card-body bootstrap-select-1">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">{{ form.date.label }} :</label>
                                        {{ form.date }}
                                    </div><!-- end form-group -->
                                </div><!-- end col -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">{{ form.attendance.label }} :</label>
                                        {{ form.attendance }}
                                    </div><!-- end form-group -->
                                </div><!-- end col -->
                            </div><!-- end row -->

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">{{ form.punchin_time.label }} :</label>
                                        {{ form.punchin_time }}
                                    </div><!-- end form-group -->
                                </div><!-- end col -->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label for="name">{{ form.punchout_time.label }} :</label>
                                        {{ form.punchout_time }}
                                    </div><!-- end form-group -->
                                </div><!-- end col -->
                            </div><!-- end row -->

                        </div><!-- end card-body -->
                    </div><!-- end card -->

                    <button type="submit" id="submit" class="btn btn-soft-primary btn-sm waves-effect waves-light">Save Changes</button>
                    <button type="button" onclick="window.history.back()" class="btn btn-soft-danger btn-sm">Cancel</button>
                </div><!-- end col -->
            </div><!-- end row -->
        </form><!-- end form -->
    </div><!-- container -->
</div><!-- end page content -->
{% endblock content %}

{% block static %}
{% load static %}
<!-- Additional styles if necessary -->
{{ form.media }}
<style>
    .form-group {
        margin-bottom: 10px;
    }
    .form-control {
        height: calc(2.8em + .75rem + 2px);
    }
</style>

{% endblock %}

templates/admin_panel/pages/attendence/attendence_list.html
{% extends 'admin_panel/base.html' %}
{% load static %}
{% load main_templates_tags %}

{% block content %}
    <!-- Page Content-->
    <div class="page-content">

        <div class="container-fluid">
            <!-- Page-Title -->
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box">
                        <div class="row">
                            <div class="col-lg-8">
                                <h4 class="page-title">{{page_title}}</h4>
                            </div><!--end col-->
                            <div class="col-lg-4 col-sm-2 float-right ml-auto">
                                <form method="get" action="{% url 'staff:staff_list' %}">
                                    <li class="list-inline-item w-100">
                                        <div class="input-group">
                                            <input name="q" type="text" id="search_box" placeholder="search" value=""
                                                class="form-control" />
                                            <span class="input-group-append">
                                                <button type="submit" class="btn btn-soft-primary btn-sm"><i class="fas fa-search"></i></button>
                                            </span>
                                        </div>
                                    </li>
                                </form>
                            </div>
                        </div><!--end row-->                                                              
                    </div><!-- end page-title-box -->
                </div><!--end col-->
            </div><!--end row-->
            <!-- end page title end breadcrumb -->
            <div class="row">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-header d-flex">
                            <div class="col-lg-4">
                                <h4 class="card-title">List view</h4>
                            </div>
                            <div class="col-md-8 text-right">
                                {% comment %} <a href="javascript:void('0');" id="print_button" class="btn btn-light text-capitalize border-0 ripple-surface-dark" style="color:#000"><i class="ri-printer-line text-primary" style="color:#3f51b5;"></i> Print</a>
                                <a href="javascript:void('0');" id="export_button" class="btn btn-light text-capitalize border-0 ripple-surface-dark" style="color:#000"><i class="ri-file-excel-2-line text-danger"></i> Export</a> {% endcomment %}
                                <div class="dropdown" style="display: inline;width: max-content;">
                                    <button class="btn btn-info dropdown-toggle" type="button" id="filterMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        <i class="ri-filter-fill"></i> Filter
                                    </button>
                                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="filterMenuButton">
                                        <form action="." method="GET" class="px-4 py-3">
                                            <div class="form-group">
                                                <label for="inputField">Select Date</label>
                                                <input type="text" id="reportrange" class="form-control" name="date_range" value="{% if not filter_data.date_range %}{{first_date_formatted}} - {{last_date_formatted}}{% else %}{{filter_data.date_range}}{% endif %}" style="display: inline;width: max-content;">
                                            </div>
                                            <div class="form-group">
                                                <label for="inputField">Name</label>
                                                {% comment %} <select class="form-control" name="branch">
                                                    {% get_branches as branches %}
                                                    <option value="">All</option>
                                                    {% for branch in branches %}
                                                    <option value="{{branch.pk}}" {% if filter_data.branch|stringformat:"s" == branch.pk|stringformat:"s" %}selected{% endif %}>{{branch.name}}</option>
                                                    {% endfor %}
                                                </select> {% endcomment %}
                                            </div>
                                            <div class="form-group">
                                                <label for="inputField">Location</label>
                                            </div>
                                            <button type="submit" class="btn btn-primary">Apply</button>
                                      </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--end card-header-->
                        <div class="card-body">
                            
                            <div class="table-responsive">
                                <table class="table mb-0" style="width:100%;">
                                    <thead>
                                        <tr>
                                            <th class="font-weight-bold text-center">#</th>
                                            <th class="font-weight-bold text-left">Staff</th>
                                            <th class="font-weight-bold text-left">Date</th>
                                            <th class="font-weight-bold text-left">Punch In Time</th>
                                            <th class="font-weight-bold text-left">Punch Out Time</th>
                                            <th class="font-weight-bold text-right">Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% load el_pagination_tags %}
                                        {% paginate 10 instances %}

                                        {% for instance in instances %}
                                        <tr>
                                            <td class="text-center">{{forloop.counter}}</td>
                                            <td class="text-left">{{instance.staff}}</td>
                                            <td class="text-left">{{instance.date}}</td>
                                            <td class="text-left">{{instance.punchin_time}}</td>
                                            <td class="text-left">{{instance.punchout_time}}</td>
                                            <td class="text-right">
                                                <!-- <a href="{% url 'staff:staff_info' pk=instance.pk %}"><i class="las la-eye text-info font-18"></i></a> -->
                                                <a href="{% url 'staff:attendence_edit' pk=instance.pk %}"><i class="las la-pen text-info font-18"></i></a>
                                                <a href="{% url 'staff:attendance_delete' pk=instance.pk %}" class="action-button remove btn btn-default btn-icon" style="padding:0;"
                                                 data-id="{{instance.pk}}" data-text="{{confirm_delete_message}}" data-title="Are you sure?" href=""><i class="las la-trash-alt text-danger font-18"></i></a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                                <!--end /table-->
                                {% get_pages %}
                                <div class="clearfix"></div>
                                <div class="row pagi my-3">
                                    <div class="col-sm-6 col-xs-6 text-left my-pagina">{% show_pages %}</div>
                                    <div class="col-sm-6 col-xs-6 text-right tot my-pagination align-items-center">
                                        <div class="m-t-10">
                                            Showing {{title}}
                                            <span class="current_page_index">{{ pages.current_start_index }}</span> - <span
                                                class="current_end_status">{{ pages.current_end_index }}</span> of <span
                                                class="total_count">{{ pages.total_count }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!--end /tableresponsive-->
                            <!-- pagination -->
                            
                        </div>
                        <!--end card-body-->
                    </div>
                    <!--end card-->
                </div> <!-- end col -->
            </div>
        </div><!-- container -->
    <!-- end page content -->
{% endblock content %}


{% block static %}
{% load static %}


{% endblock static %}
    
        